#### Stand-alone repos
[pr-agent-pro]
best_practices_paths=["pr-agent-pro"]


##### Repos related to groups
# frontend_repos
[codium-ai-platform-client]
best_practices_paths=["groups/frontend_repos"]

# backend_repos
[qodo-engine]
best_practices_paths=["groups/backend_repos"]

# multi-group repos
[qodo-gen-chat-webview]
best_practices_paths=["groups/frontend_repos", "groups/backend_repos"]


#### Monorepos
[pr-agent-devops]

[pr-agent-devops.pr_agent_app]
best_practices_paths = ["pr-agent-devops/pr_agent_app"]

[pr-agent-devops.helm-nextgen-values]
best_practices_paths = ["pr-agent-devops/helm-nextgen-values"]
